disabled_rules:
  - trailing_whitespace
  - comment_spacing
  - identifier_name
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - function_parameter_count
  - nesting
  - file_length
  - switch_case_alignment

line_length: 300

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
