# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :tests do
    params = {
      package_path: '.',
      scheme: 'OpenID4VCI',
      destination: "platform=iOS Simulator,name=iPhone 16,OS=18.5",
      result_bundle: true
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)
  end

  desc "Fix lint issues"
  lane :run_lint do
    sh "swiftlint lint --fix --config ../.swiftlint.yml --quiet ../"
  end

  desc "Code coverage"
  lane :code_coverage do
    
    UI.message("PWD: #{Dir.pwd}")
    sh("ls -la")
    sh("ls -la xcov_output || true")
    sh("find . -name '*.xcresult' -maxdepth 4 || true")

    params = {
      package_path: '.',
      scheme: 'OpenID4VCI',
      destination: "platform=iOS Simulator,name=iPhone 16,OS=18.5",
      output_directory: "xcov_output",
      result_bundle: true,
      parallel_testing: false,
      xcodebuild_formatter: "xcbeautify"
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)

    xcov(
      scheme: "OpenID4VCI",
      output_directory: "xcov_output",
      is_swift_package: true,
      minimum_coverage_percentage: 50.0,
      include_targets: "OpenID4VCI"
    )

    if ENV['CI'] != 'true'
      sh 'open ../xcov_output/index.html'
    end
  end

  desc "Builds the package"
  lane :just_build do
    xcodebuild(
      scheme: "OpenID4VCI",
      destination: "platform=iOS Simulator,name=iPhone 16,OS=18.5",
      xcargs: "-skipPackagePluginValidation -disableAutomaticPackageResolution"
    )
  end

  before_all do
    FileUtils.remove_dir '../xcov_output', true
  end
  
end
