# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs unit tests"
  lane :tests do
    params = {
      package_path: '.',
      scheme: 'OpenID4VCI',
      devices: ['iPhone 14'], 
      result_bundle: true
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)
  end

  desc "Code coverage"
  lane :code_coverage do
    
    # You can convert the generated report to JSON using the following command:
    # xcrun xccov view xcov_output/xccovreport-0.xccovreport --json
    
    params = {
      package_path: '.',
      scheme: 'OpenID4VCI',
      devices: ['iPhone 14'], 
      output_directory: "xcov_output",
      result_bundle: true
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)

    xcov(
      scheme: "OpenID4VCI",
      output_directory: "xcov_output",
      is_swift_package: true,
      minimum_coverage_percentage: 30.0
    )
    if ENV['CI'] != 'true'
      sh 'open ../xcov_output/index.html'
    end
  end

  desc "Builds the package"
  lane :just_build do
    xcodebuild(
      scheme: "OpenID4VCI",
      destination: "platform=iOS Simulator,OS=16.2,name=iPhone 8",
      xcargs: "-skipPackagePluginValidation -disableAutomaticPackageResolution"
    )
  end

  before_all do
    FileUtils.remove_dir '../xcov_output', true
  end
  
end
