---
name: build-package
on:
  pull_request:
    types: [opened, reopened]
  push:

jobs:
  build:
    runs-on: macos-latest
    env:
      IOS_SIMULATOR_DEVICE: iPhone 17
      IOS_SIMULATOR_OS: latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.1'
      - uses: actions/checkout@v4
      - run:
          fastlane tests